from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Dict, Iterable, List

from academic_pe.contracts.models import ArtifactContract


@dataclass
class DriftCheckResult:
    passed: bool
    issues: List[str] = field(default_factory=list)


def run_all(contract: ArtifactContract, context: Dict[str, str]) -> DriftCheckResult:
    filtered_context = {k: v for k, v in context.items() if k != "document_plan"}
    combined: List[str] = []
    for check_fn in [
        check_ai_markers,
        check_genre_style_markers,
        check_academic_drift,
        check_forbidden_visualization,
        check_forbidden_citations,
        check_forbidden_title_page,
        check_forbidden_rubric,
    ]:
        result = check_fn(contract, filtered_context)
        if not result.passed:
            combined.extend(result.issues)
    return DriftCheckResult(passed=len(combined) == 0, issues=combined)


def check_ai_markers(contract: ArtifactContract, context: Dict[str, str]) -> DriftCheckResult:
    if not _forbids(contract, "ai_markers"):
        return DriftCheckResult(passed=True)

    patterns = [
        r"\bas an ai\b",
        r"\bas a language model\b",
        r"\bi cannot (?:write|create|generate)\b",
        r"\bgenerated by ai\b",
        r"\bthis (?:text|document|response) was generated\b",
        r"\bi (?:apologize|am sorry)\b",
        r"\bsorry,?\s+(?:but\s+)?i\b",
        r"\bhere (?:is|are)'?s?\s+(?:the\s+)?(?:requested|draft|final)\b",
        r"\bin this (?:response|answer),?\s+i\b",
        r"\[insert [^\]]+\]",
        r"\[placeholder[^\]]*\]",
        r"\[(?:todo|tbd|draft|section|add [^\]]+)\]",
        r"<(?:insert|placeholder|todo|tbd)[^>]*>",
        r"\blorem ipsum\b",
        r"\btemplate filler\b",
        r"\bdisclaimer\b",
        r"\bthis document does not\b",
        r"\bplease note that\b",
        r"\bfeel free to\b",
        r"\bhope this helps\b",
        r"\bif you have any questions\b",
        r"\bimportant note\b",
        r"\bnote:\s",
        r"\bfor the purposes of this\b",
        r"\bdue to safety guidelines\b",
        r"\bdelve\b",
        r"\btestament\b",
    ]
    return _scan_patterns(context, patterns, "contains AI/meta or placeholder marker")


def check_genre_style_markers(contract: ArtifactContract, context: Dict[str, str]) -> DriftCheckResult:
    if contract.artifact == "creative_poem":
        return _scan_patterns(
            context,
            [
                r"^\s{0,3}#{1,3}\s*(?:analysis|meaning|explanation)\s*$",
                r"^\s*(?:analysis|meaning|explanation)\s*:\s+",
                r"\bthis poem (?:explores|shows|symbolizes|is about)\b",
                r"\bthe poem (?:explores|shows|symbolizes|is about)\b",
            ],
            "contains explanatory prose instead of artifact-native poetic text",
        )

    if contract.artifact == "creative_story":
        return _scan_patterns(
            context,
            [
                r"^\s{0,3}#{1,3}\s*(?:summary|story summary|moral)\s*$",
                r"^\s*(?:summary|story summary)\s*:\s+",
                r"\bthis story (?:is about|follows|explores|teaches)\b",
                r"\bthe story (?:is about|follows|explores|teaches)\b",
                r"\bin this story,?\s+",
            ],
            "contains summary or explanatory prose instead of artifact-native narrative",
        )

    if contract.artifact == "school_essay":
        return _scan_patterns(
            context,
            [
                r"\bmethodological framework\b",
                r"\bpeer-reviewed literature\b",
                r"\bstatistically significant\b",
                r"\bempirical evidence demonstrates\b",
                r"\bthis research paper\b",
            ],
            "contains professional research register inappropriate for a school essay",
        )

    if contract.artifact == "technical_readme":
        return _scan_patterns(
            context,
            [
                r"\bthis paper (?:examines|analyzes|argues)\b",
                r"\bthe present study\b",
                r"\bliterature review\b",
                r"\bmethodology\b",
            ],
            "contains academic prose inappropriate for a technical README",
        )

    if contract.artifact == "academic_paper":
        return _scan_patterns(
            context,
            [
                r"\bit is important to note that\b",
                r"\bin today's world\b",
                r"\bthere are many different perspectives\b",
                r"\bthis topic is very interesting\b",
                r"\bthroughout history,?\s+",
            ],
            "contains generic filler inappropriate for academic prose",
        )

    return DriftCheckResult(passed=True)


def check_academic_drift(contract: ArtifactContract, context: Dict[str, str]) -> DriftCheckResult:
    if not (_forbids(contract, "academic_drift") or _forbids(contract, "research_paper_structure")):
        return DriftCheckResult(passed=True)

    patterns = [
        r"^\s{0,3}#{1,3}\s*abstract\s*$",
        r"^\s{0,3}#{1,3}\s*methodology\s*$",
        r"^\s{0,3}#{1,3}\s*methods?\s*$",
        r"^\s{0,3}#{1,3}\s*literature review\s*$",
        r"^\s{0,3}#{1,3}\s*references\s*$",
        r"^\s{0,3}#{1,3}\s*bibliography\s*$",
        r"^\s*abstract\s*:\s+",
        r"^\s*methodology\s*:\s+",
        r"^\s*literature review\s*:\s+",
    ]
    return _scan_patterns(context, patterns, "contains academic-paper structure forbidden by contract")


def check_forbidden_visualization(contract: ArtifactContract, context: Dict[str, str]) -> DriftCheckResult:
    if contract.visualization_required:
        return DriftCheckResult(passed=True)
    if not _forbids(contract, "forced_visualization"):
        return DriftCheckResult(passed=True)

    patterns = [
        r"```python-run\b",
        r"!\[[^\]]*\]\([^)]*(?:plot|chart|graph|exports/)[^)]*\)",
    ]
    return _scan_patterns(context, patterns, "contains visualization artifact forbidden by contract")


def check_forbidden_citations(contract: ArtifactContract, context: Dict[str, str]) -> DriftCheckResult:
    if not _forbids(contract, "citations"):
        return DriftCheckResult(passed=True)

    patterns = [
        r"^\s{0,3}#{1,3}\s*references\s*$",
        r"^\s{0,3}#{1,3}\s*bibliography\s*$",
        r"\[[A-ZА-Я][A-Za-zА-Яа-я-]+,\s*\d{4}\]",
        r"\([A-ZА-Я][A-Za-zА-Яа-я-]+,\s*\d{4}\)",
        r"\[\d+\]",
    ]
    return _scan_patterns(context, patterns, "contains citations or reference apparatus forbidden by contract")


def check_forbidden_title_page(contract: ArtifactContract, context: Dict[str, str]) -> DriftCheckResult:
    if not _forbids(contract, "title_page"):
        return DriftCheckResult(passed=True)

    patterns = [
        r"^\s{0,3}#{1,3}\s*title page\s*$",
        r"^\s*author\s*:\s+",
        r"^\s*institution\s*:\s+",
        r"^\s*course\s*:\s+",
    ]
    return _scan_patterns(_first_lines(context, 12), patterns, "contains title-page apparatus forbidden by contract")


def check_forbidden_rubric(contract: ArtifactContract, context: Dict[str, str]) -> DriftCheckResult:
    if not _forbids(contract, "rubric"):
        return DriftCheckResult(passed=True)

    patterns = [
        r"^\s{0,3}#{1,3}\s*(?:evaluation criteria|grading criteria|rubric)\s*$",
        r"^\s*(?:evaluation criteria|grading criteria|rubric)\s*:\s+",
    ]
    return _scan_patterns(context, patterns, "contains rubric or grading criteria forbidden by contract")


def _scan_patterns(context: Dict[str, str], patterns: Iterable[str], message: str) -> DriftCheckResult:
    compiled = [re.compile(pattern, re.IGNORECASE | re.MULTILINE) for pattern in patterns]
    issues: List[str] = []
    for section, text in context.items():
        text = text or ""
        for pattern in compiled:
            match = pattern.search(text)
            if match:
                line = text[: match.start()].count("\n") + 1
                issues.append(f"Section '{section}' line {line} {message}: {match.group(0).strip()[:80]}")
                break
    return DriftCheckResult(passed=len(issues) == 0, issues=issues)


def _first_lines(context: Dict[str, str], limit: int) -> Dict[str, str]:
    return {
        section: "\n".join((text or "").splitlines()[:limit])
        for section, text in context.items()
    }


def _forbids(contract: ArtifactContract, name: str) -> bool:
    return name in set(contract.forbid)
