from typing import Optional
from src.core.config import AgentConfig
from src.core.llm import LLMClient

class BaseAgent:
    """
    Represents an AI Agent with a specific role, configuration, and access to an LLM.
    """
    def __init__(self, config: AgentConfig, llm_client: LLMClient):
        self.config = config
        self.llm = llm_client

    def process(self, task_description: str, context: Optional[str] = None) -> str:
        """
        Executes a task using the agent's specific configuration.

        Args:
            task_description: The specific instruction for this step (User Prompt).
            context: Optional background information to append to the system prompt.

        Returns:
            The text generated by the LLM.
        """
        # Combine static system prompt with dynamic context if provided
        system_prompt = self.config.system_prompt
        if context:
            system_prompt += f"\n\n[Context Data]\n{context}"

        return self.llm.generate(
            system_prompt=system_prompt,
            user_prompt=task_description,
            model=self.config.model
        )
